### ISSUE TITLE
More than 2020 dates

### ISSUE THREAD

**Issue by andrew-vancil** [degauss-org/jfs_aggregated_data_report#5]
Investigate why we only got 2020 results on the first run

**Comment by andrew-vancil** [comment]
I trying to build and test the updated container, but I'm having a heck of a time with it. Would you guys be able to take a peek? @cole-brokamp @erikarasnick 

When I do the build, I run into trouble when Docker is trying to restore the renv. The packages run along installing, but then it errors out and this is the message I get:

> 12 29.74 Error: failed to retrieve package 'crayon'
#12 29.74 In addition: Warning messages:
#12 29.74 1: failed to retrieve package 'cli' 
#12 29.74 2: internal error: unexpected status code 'structure(list(message = "failed to retrieve package 'cli'", call = NULL, traceback = c("Traceback (most recent calls last):", "24: renv::restore(repos = c(CRAN = \"https://packagemanager.rstudio.com/all/__linux__/focal/latest\"))", "23: renv_restore_run_actions(project, diff, current, lockfile, rebuild)", "22: renv_retrieve(packages)", "21: handler(package, renv_retrieve_impl(package))", "20: renv_retrieve_impl(package)", "19: renv_retrieve_repos(record)", "18: catch(withCallingHandlers(method(record), renv.retrieve.error = function(error) {",  "        errors$push(error)", "    }))", "17: tryCatch(withCallingHandlers(expr, error = renv_error_capture), ", "        error = renv_error_tag)", "16: tryCatchList(expr, classes, parentenv, handlers)", "15: tryCatchOne(expr, names, parentenv, handlers[[1L]])", "14: doTryCatch(return(expr), name, parentenv, handler)", "13: withCallingHandlers(expr, error = renv_error_capture)", "12: withCallingHandlers(m [... truncated] 
#12 29.74 3: curl: (22) The requested URL returned error: 404  
#12 29.74 Traceback (most recent calls last):
#12 29.74 8: renv::restore(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/focal/latest"))
#12 29.74 7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
#12 29.74 6: renv_retrieve(packages)
#12 29.74 5: handler(package, renv_retrieve_impl(package))
#12 29.74 4: renv_retrieve_impl(package)
#12 29.74 3: renv_retrieve_repos(record)
#12 29.74 2: stopf("failed to retrieve package '%s'", record$Package)
#12 29.74 1: stop(sprintf(fmt, ...), call. = call.)
#12 29.74 Execution halted
--
executor failed running [/bin/sh -c R --quiet -e "renv::restore(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'))"]: exit code: 1


Ok, so I removed the package "crayon" (which appears to be part of the tidyverse) and the build works. However, I run the container using make test, and I run into more issues:

> 
>  docker run --rm -v "/Users/vanug6/R/jfs_aggregated_data_report/test":/tmp docker.io/degauss/jfs_aggregated_data_report simulated_jfs_edge_data_geocoded.csv
> 
> Neighborhood results with < 5 instances have been censored for privacy purposes
> 
> Warning message:
> package ‘readr’ was built under R version 4.0.5 
> Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  namespace ‘pillar’ 1.4.7 is already loaded, but >= 1.6.0 is required
> In addition: Warning message:
> package ‘tidyverse’ was built under R version 4.0.4 
> Execution halted
> make: *** [test] Error 1

Ok, so then I check "pillar" and it is installed and in the lockfile at version 1.7.0. It also looks like the package "crayon" is a dependency of "pillar". I've tried removing "pillar" as well from the lockfile, but I get the same exact error. I updated everything in my environment, but that doesn't seem to be helping at all either. 

Have you run into something like this? Thanks for the help!

**Comment by cole-brokamp** [comment]
In general, I would never manually edit the lockfile.  Its designed to capture a working set of packages and their versions at a single point of time.   Once we start changing things, its not guaranteed to work anymore.

**Comment by andrew-vancil** [comment]
I changed the top of the Docker file to "FROM rocker/verse:4.1.2", which matches my system and the lockfile, but I still got the error about the "crayon" package when I try to build. 

However,  tried changing the `renv::restore(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'))` back to `renv::restore(repos = c(CRAN = 'https://cran.rstudio.com'))` and the container built and ran properly. Is it ok if I use this other code? It took a long time to build, but it did work. The switch is at lines 20 & 21 in the dockerfile

**Comment by cole-brokamp** [comment]
Yes, that's fine.  Its likely a problem with the binaries hosted on RSPM.  We've had this issue before too and CRAN works fine, but does take a lot longer.
